# ===========================================================================
# Project:    https://github.com/gmacario/easy-genivigo
# File:       docker-compose.yml
#
# See also:
# - Compose file reference: https://docs.docker.com/compose/compose-file/
# ===========================================================================

version: '2'

services:
  goserver:
    image: gocd/gocd-server:16.2.1
    # build: mygenivigo
    ports:
      - "8153:8153"
    # tty: true
    # privileged: true

  # goagent-yocto-genivi:
  #   image: gmacario/build-yocto-genivi:latest
  #   user: go
  #   working_dir: "/var/lib/go-agent"
  #   # entrypoint: ""
  #   command: "/usr/local/bin/run-gocd-agent.sh"
  #   environment:
  #     - GO_SERVER=goserver
  #   # links:
  #   #     - mygenivigo:master
  #   #   volumes:
  #   #     - data:/home/genivigo

# volumes:
#     data:
#     downloads:
#     sstate-cache:

# EOF
